INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Yucas Gui-Gui","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Papas Gui-gui","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Harina Pan","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Berengena Vidrio Pqño","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Aceitunas de Vidrio","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Aceitunas De lata","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Aceite de litro","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Aceite Galon","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Adereso de Papas","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Miel Pore","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Leche de Coco","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Papitas mini Gui-gui","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Pepinillos Latas","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Mostaza Dulce","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Vinagre de Arroz","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Berengena en Lata","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("panko naranja","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("panko Clasico","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Ketchup Potes Grandes","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Condimentos Shawarma","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Condimentos hot red parrika","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Condimentos Rosemary","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Aceite de Oliva","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Cajun Spaci Mixture","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BBQ picante","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Condimentos gand de Green dili","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Cajun Seasoning","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Ground Allspice","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Red Pipper","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Curry Power","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Kabab","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Sasonador Fajitas","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Taco Seasonin","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Bacon Flavored","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Piklin Spice","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Vino Blanco","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Vinagre","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BBQ","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Atun Agua","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Ajonjoli","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Blody mary pqño","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Sal","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Union Osem","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("paprika","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("salmon entero","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("salmon ahumado","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pastrami ny","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pavo ahumado","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pavo natural","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pastrami de pavo","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pavo delight","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("robalo fileteado","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("muslos de pollo","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("alitas de pollo importadas","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("alitas de pollo nacionales","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pan baguett Ny","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pan baguett nacional","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("salchichas de pollo","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("salchichas de carne","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("tilapía","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("mantequilla","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("atun importado","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("atun nacional","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("cornbeef","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("nugguets empire","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("nugguets para la cocina","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("kibes","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("cigarritos","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pan pita","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("cangrejo picado","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("cangrejo largo","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("milanesa de pollo","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("milanesa de carne","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("carne para fajitas","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Carne molida","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Ryb eye 300","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Ryb eye 500","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("salami","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("bolonga","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("crema wheep","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("tortas ahava","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ryb eye entero","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("galletas de triangulito","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("agua mineral","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("agua sparkling","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("cocacola de botella","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("cocacola light de botella","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("box de cocacola","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("box de cocacola light","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("box de chinotto","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("box de nestea","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("scallops","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("chistorras","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("mayonesa","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Mostaza","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("jugos de manzana lata","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("jugo de manzana botellita","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("jugos de manazana de 1litro","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("aceitunas negras","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("aceitunas verdes rellenas de pimenton","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("comino","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("mostaza en sobres","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ketchup en sobres","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("mayonesa en sobres","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("soya en sobre","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("soya de galon","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("salsa teriyaky","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("huevos","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("chocolates enteros","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("pasas secas","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("soya en dispensador","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("crema de ajonjoli","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("vino tinto","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("wishky","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("azucar de saco","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("azucar de sobresito","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("Splenda","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("lumpias","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("harina de trigo","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("","ALIMENTICIO",10);