INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("YUCAS GUI-GUI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPAS GUI-GUI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("HARINA PAN","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BERENGENA VIDRIO PQÑO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS DE VIDRIO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS DE LATA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITE DE LITRO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITE GALON","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ADERESO DE PAPAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MIEL PORE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("LECHE DE COCO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPITAS MINI GUI-GUI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PEPINILLOS LATAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOSTAZA DULCE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINAGRE DE ARROZ","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BERENGENA EN LATA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PANKO NARANJA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PANKO CLASICO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KETCHUP POTES GRANDES","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS SHAWARMA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS HOT RED PARRIKA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS ROSEMARY","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITE DE OLIVA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CAJUN SPACI MIXTURE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BBQ PICANTE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS GAND DE GREEN DILI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CAJUN SEASONING","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("GROUND ALLSPICE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RED PIPPER","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CURRY POWER","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KABAB","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SASONADOR FAJITAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TACO SEASONIN","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BACON FLAVORED","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PIKLIN SPICE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINO BLANCO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINAGRE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BBQ","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ATUN AGUA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AJONJOLI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BLODY MARY PQÑO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SAL","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("UNION OSEM","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPRIKA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALMON ENTERO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALMON AHUMADO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PASTRAMI NY","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAVO AHUMADO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAVO NATURAL","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PASTRAMI DE PAVO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAVO DELIGHT","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ROBALO FILETEADO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MUSLOS DE POLLO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ALITAS DE POLLO IMPORTADAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ALITAS DE POLLO NACIONALES","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAN BAGUETT NY","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAN BAGUETT NACIONAL","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALCHICHAS DE POLLO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALCHICHAS DE CARNE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TILAPÍA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MANTEQUILLA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ATUN IMPORTADO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ATUN NACIONAL","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CORNBEEF","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("NUGGUETS EMPIRE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("NUGGUETS PARA LA COCINA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KIBES","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CIGARRITOS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAN PITA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CANGREJO PICADO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CANGREJO LARGO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MILANESA DE POLLO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MILANESA DE CARNE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CARNE PARA FAJITAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CARNE MOLIDA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RYB EYE 300","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RYB EYE 500","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALAMI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLONGA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CREMA WHEEP","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TORTAS AHAVA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RYB EYE ENTERO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("GALLETAS DE TRIANGULITO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AGUA MINERAL","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AGUA SPARKLING","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COCACOLA DE BOTELLA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COCACOLA LIGHT DE BOTELLA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE COCACOLA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE COCACOLA LIGHT","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE CHINOTTO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE NESTEA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SCALLOPS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CHISTORRAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MAYONESA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOSTAZA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JUGOS DE MANZANA LATA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JUGO DE MANZANA BOTELLITA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JUGOS DE MANAZANA DE 1LITRO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS NEGRAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS VERDES RELLENAS DE PIMENTON","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COMINO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOSTAZA EN SOBRES","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KETCHUP EN SOBRES","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MAYONESA EN SOBRES","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SOYA EN SOBRE","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SOYA DE GALON","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALSA TERIYAKY","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("HUEVOS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CHOCOLATES ENTEROS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PASAS SECAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SOYA EN DISPENSADOR","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CREMA DE AJONJOLI","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINO TINTO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("WISHKY","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AZUCAR DE SACO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AZUCAR DE SOBRESITO","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SPLENDA","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("LUMPIAS","ALIMENTICIO",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("HARINA DE TRIGO","ALIMENTICIO",10);

INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ROLLOS DE CAJA DOBLE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VASOS DE VIDRIOS GRD","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SERVILLETAS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPEL SCOT","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MANTELES CAFÉ HILEL","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PITILLITOS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PITILLOS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("DESINFECTANTE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JABON LIQUIDO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CLORO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COLETOS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PALLOS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MR MUSCULO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("LIMPIA VIDRIO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CUCHARITAS DE PLASTICO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KIT TENEDOR Y CUCHILLO DE PLASTICO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ESPONJAS AMARILLA Y VERDE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ESPONJA DE ALUMINIO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ROLLO SIMPLE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PIEDRAS PARA PARRILLA","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PINZAS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CUCHILLOS DE SIERRA","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TENEDOR Y CUCHILLO DE METAL","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MANTELES DE TELA","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COPAS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("DELANTALES DE CAFÉ HILEL","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PLATOS DE VIDRIO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PLATOS DE CERAMICA","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TABLAS DE MADERA PARA CARNE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PALITOS CHINOS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS DE 20 KG","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS DE 10 KG","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS PARA EMBASAR AL VACIO GRANDE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS PARA EMBASAR AL VACIO PQÑO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MESAS DE PLASTICO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOMBILLOS DE CAMPANA","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOMBILLOS DE LAMP COLGANTES","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("GUANTES DE LATEX","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SARTENES EN VOL","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SARTENES DE TEFLON","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TOPEERWER","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ESPONJAS JABONOSAS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOPAS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("EMBASES DE PLASTICOS CUADRADOS GRANDE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("EMBASES DE PLASTICOS CUADRADOS PQÑO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("POTES CHINOS GRANDE","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("POTES CHINOS MEDIANO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("POTES CHINOS PQÑO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("EMBASES DE PLASTICOS TRIANGULARES","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("EMBASES DE PLASTICOS REDONDOS","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPEL ALUMINIO","PAPELERIA",10);
INSERT INTO PRODUCTO (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPEL ENVOPLAST","PAPELERIA",10);