INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("YUCAS GUI-GUI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPAS GUI-GUI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("HARINA PAN","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BERENGENA VIDRIO PEQUEÑO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS DE VIDRIO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS DE LATA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITE DE LITRO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITE GALON","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ADERESO DE PAPAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MIEL PORE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("LECHE DE COCO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPITAS MINI GUI-GUI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PEPINILLOS LATAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOSTAZA DULCE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINAGRE DE ARROZ","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BERENGENA EN LATA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PANKO NARANJA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PANKO CLASICO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KETCHUP POTES GRANDES","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS SHAWARMA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS HOT RED PARRIKA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS ROSEMARY","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITE DE OLIVA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CAJUN SPACI MIXTURE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BBQ PICANTE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CONDIMENTOS GAND DE GREEN DILI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CAJUN SEASONING","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("GROUND ALLSPICE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RED PIPPER","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CURRY POWER","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KABAB","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SASONADOR FAJITAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TACO SEASONIN","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BACON FLAVORED","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PIKLIN SPICE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINO BLANCO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINAGRE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BBQ","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ATUN AGUA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AJONJOLI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BLODY MARY PEQUEÑO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SAL","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("UNION OSEM","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPRIKA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALMON ENTERO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALMON AHUMADO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PASTRAMI NY","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAVO AHUMADO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAVO NATURAL","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PASTRAMI DE PAVO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAVO DELIGHT","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ROBALO FILETEADO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MUSLOS DE POLLO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ALITAS DE POLLO IMPORTADAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ALITAS DE POLLO NACIONALES","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAN BAGUETT NY","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAN BAGUETT NACIONAL","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALCHICHAS DE POLLO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALCHICHAS DE CARNE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TILAPÍA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MANTEQUILLA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ATUN IMPORTADO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ATUN NACIONAL","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CORNBEEF","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("NUGGUETS EMPIRE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("NUGGUETS PARA LA COCINA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KIBES","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CIGARRITOS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAN PITA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CANGREJO PICADO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CANGREJO LARGO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MILANESA DE POLLO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MILANESA DE CARNE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CARNE PARA FAJITAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CARNE MOLIDA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RYB EYE 300","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RYB EYE 500","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALAMI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLONGA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CREMA WHEEP","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TORTAS AHAVA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("RYB EYE ENTERO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("GALLETAS DE TRIANGULITO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AGUA MINERAL","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AGUA SPARKLING","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COCACOLA DE BOTELLA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COCACOLA LIGHT DE BOTELLA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE COCACOLA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE COCACOLA LIGHT","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE CHINOTTO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOX DE NESTEA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SCALLOPS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CHISTORRAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MAYONESA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOSTAZA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JUGOS DE MANZANA LATA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JUGO DE MANZANA BOTELLITA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JUGOS DE MANAZANA DE 1LITRO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS NEGRAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ACEITUNAS VERDES RELLENAS DE PIMENTON","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COMINO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOSTAZA EN SOBRES","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KETCHUP EN SOBRES","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MAYONESA EN SOBRES","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SOYA EN SOBRE","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SOYA DE GALON","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SALSA TERIYAKY","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("HUEVOS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CHOCOLATES ENTEROS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PASAS SECAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SOYA EN DISPENSADOR","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CREMA DE AJONJOLI","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VINO TINTO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("WISHKY","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AZUCAR DE SACO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("AZUCAR DE SOBRESITO","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SPLENDA","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("LUMPIAS","ALIMENTICIO",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("HARINA DE TRIGO","ALIMENTICIO",10);

INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ROLLOS DE CAJA DOBLE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("VASOS DE VIDRIOS GRD","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SERVILLETAS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPEL SCOT","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MANTELES CAFÉ HILEL","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PITILLITOS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PITILLOS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("DESINFECTANTE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("JABON LIQUIDO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CLORO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COLETOS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PALLOS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MR MUSCULO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("LIMPIA VIDRIO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CUCHARITAS DE PLASTICO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("KIT TENEDOR Y CUCHILLO DE PLASTICO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ESPONJAS AMARILLA Y VERDE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ESPONJA DE ALUMINIO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ROLLO SIMPLE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PIEDRAS PARA PARRILLA","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PINZAS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("CUCHILLOS DE SIERRA","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TENEDOR Y CUCHILLO DE METAL","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MANTELES DE TELA","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("COPAS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("DELANTALES DE CAFÉ HILEL","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PLATOS DE VIDRIO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PLATOS DE CERAMICA","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TABLAS DE MADERA PARA CARNE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PALITOS CHINOS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS DE 20 KG","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS DE 10 KG","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS PARA EMBASAR AL VACIO GRANDE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOLSAS PARA EMBASAR AL VACIO PEQUEÑO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MESAS DE PLASTICO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOMBILLOS DE CAMPANA","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("BOMBILLOS DE LAMP COLGANTES","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("GUANTES DE LATEX","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SARTENES EN VOL","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("SARTENES DE TEFLON","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("TOPEERWER","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ESPONJAS JABONOSAS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("MOPAS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ENVASES DE PLASTICOS CUADRADOS GRANDE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ENVASES DE PLASTICOS CUADRADOS PEQUEÑO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("POTES CHINOS GRANDE","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("POTES CHINOS MEDIANO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("POTES CHINOS PEQUEÑO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ENVASES DE PLASTICOS TRIANGULARES","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("ENVASES DE PLASTICOS REDONDOS","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPEL ALUMINIO","PAPELERA",10);
INSERT INTO PRODUCTOS (NOMBRE,TIPO,CANTIDAD_MINIMA)
VALUES ("PAPEL ENVOPLAST","PAPELERA",10);

----------------------------------------------
insert into fecha_productos (fecha_adquisicion,hora_adquisicion,id_producto,cantidad_inicial,cantidad_actual,fecha_vencimiento,ubicacion) values (date('now'),time('now','localtime'),1,10,10,'2012-03-25',null);